### ISSUE TITLE
I'm taking suggestions for my agenda for 0.13.0

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1276]
I'd like to release Hy 0.13.0 sometime in June. Here are the things I intend to take care of in time for that release:

- [x] Change our test infrastructure to use something other than Nose (probably pytest)
- [x] Use travis-tox, or don't use Tox on Travis at all
- [x] #1230: Reader macros aren't
- [x] #1225: Policy for copyright and license notices at the start of each file
- [x] #1198: Docs versioning and readthedocs.org
  - [x] #1290: Get the documentation building again
- [x] Polish up `CONTRIBUTING.rst`

(There are other issues that bug me more than some of these but are too big for me to necessarily get to in time, like how we need to automatically test examples in the documentation.)

If there's something else you think I should tend to for this release, post your suggestion here.

**Comment by kirbyfan64** [comment]
> Change our test infrastructure to use something other than Nose (probably pytest)

Agreed. FWIW the tests mostly run already under `py.test`, though I don't recall if anything didn't work.

>  Use travis-tox, or don't use Tox on Travis at all

https://github.com/berkerpeksag/astor/pull/56

> #1230: Reader macros aren't

What was the consensus on this? It seemed to stall at "either change readers to tagged literals or rename them to something else"...

> #1198: Docs versioning and readthedocs.org

ping @paultag 

> Polish up `CONTRIBUTING.rst`

Looks fine to me...?

**Comment by Kodiologist** [comment]
>> Polish up `CONTRIBUTING.rst`
>
> Looks fine to me...?

It could use a bit more organization and explanation, and a bit fewer ampersands, slashes, and exclamation points.
