### ISSUE TITLE
Release 0.9.12

### ISSUE THREAD

**Issue by olasd** [hylang/hy#380]
Blockers:
- [x] `macroexpand` (#310 ftw)
- [x] `kwapply` and `apply` (#159, #317)
- [x] multi-`for` / `with` (#44, #325)
- [x] Multi-get (#362, #363)
- [x] gensym (#270, #374)
- [x] Arg-less `+` and `*` (#376, #372)
- [x] Reader macros (#103, #377)

Documentation:
- [x] Document gensym (#388)
- [x] Document Reader macros (#377, #404)

Nice to have:
- [x] fix meth or kick it out of contrib and write tests _cough_ (#330)
- [ ] Hy notation for the repr of objects (#351, #354)
- [x] Method call with no target crashes the compiler (#366)
- [x] Moar error reporting (latest incarnation: #302)

Post release:
- [ ] Delete our rply fork

Punt to 0.10.0:
- [ ] `-main` (lacks consensus) (#249)
- [ ] auto-`kwapply` (big change) (#295)
- [ ] REPL and multiline strings (hard to fix) (#305)
- [x] Py3.4 support (#344, #345)
